//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerOrder.ReportService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReportService.IReportService")]
    public interface IReportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetAllCustomers", ReplyAction="http://tempuri.org/IReportService/GetAllCustomersResponse")]
        System.Collections.Generic.List<EF2.Customer> GetAllCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetAllCustomers", ReplyAction="http://tempuri.org/IReportService/GetAllCustomersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EF2.Customer>> GetAllCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetAllOrdersForCustomer", ReplyAction="http://tempuri.org/IReportService/GetAllOrdersForCustomerResponse")]
        System.Collections.Generic.List<EF2.Order> GetAllOrdersForCustomer(short _customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetAllOrdersForCustomer", ReplyAction="http://tempuri.org/IReportService/GetAllOrdersForCustomerResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EF2.Order>> GetAllOrdersForCustomerAsync(short _customerId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportServiceChannel : ReportService.IReportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportServiceClient : System.ServiceModel.ClientBase<ReportService.IReportService>, ReportService.IReportService {
        
        public ReportServiceClient() {
        }
        
        public ReportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<EF2.Customer> GetAllCustomers() {
            return base.Channel.GetAllCustomers();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EF2.Customer>> GetAllCustomersAsync() {
            return base.Channel.GetAllCustomersAsync();
        }
        
        public System.Collections.Generic.List<EF2.Order> GetAllOrdersForCustomer(short _customerId) {
            return base.Channel.GetAllOrdersForCustomer(_customerId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EF2.Order>> GetAllOrdersForCustomerAsync(short _customerId) {
            return base.Channel.GetAllOrdersForCustomerAsync(_customerId);
        }
    }
}
