//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClient.ProxyReport {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/EF2")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADRESAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short CUSTOMERIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WCFClient.ProxyReport.Order> OrderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADRESA {
            get {
                return this.ADRESAField;
            }
            set {
                if ((object.ReferenceEquals(this.ADRESAField, value) != true)) {
                    this.ADRESAField = value;
                    this.RaisePropertyChanged("ADRESA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short CUSTOMERID {
            get {
                return this.CUSTOMERIDField;
            }
            set {
                if ((this.CUSTOMERIDField.Equals(value) != true)) {
                    this.CUSTOMERIDField = value;
                    this.RaisePropertyChanged("CUSTOMERID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NAME {
            get {
                return this.NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.NAMEField, value) != true)) {
                    this.NAMEField = value;
                    this.RaisePropertyChanged("NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WCFClient.ProxyReport.Order> Order {
            get {
                return this.OrderField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderField, value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/EF2")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short CUSTOMERIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFClient.ProxyReport.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DATAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ORDERIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WCFClient.ProxyReport.OrderDetails> OrderDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> VALOAREField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short CUSTOMERID {
            get {
                return this.CUSTOMERIDField;
            }
            set {
                if ((this.CUSTOMERIDField.Equals(value) != true)) {
                    this.CUSTOMERIDField = value;
                    this.RaisePropertyChanged("CUSTOMERID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFClient.ProxyReport.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DATA {
            get {
                return this.DATAField;
            }
            set {
                if ((this.DATAField.Equals(value) != true)) {
                    this.DATAField = value;
                    this.RaisePropertyChanged("DATA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ORDERID {
            get {
                return this.ORDERIDField;
            }
            set {
                if ((this.ORDERIDField.Equals(value) != true)) {
                    this.ORDERIDField = value;
                    this.RaisePropertyChanged("ORDERID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WCFClient.ProxyReport.OrderDetails> OrderDetails {
            get {
                return this.OrderDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderDetailsField, value) != true)) {
                    this.OrderDetailsField = value;
                    this.RaisePropertyChanged("OrderDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> VALOARE {
            get {
                return this.VALOAREField;
            }
            set {
                if ((this.VALOAREField.Equals(value) != true)) {
                    this.VALOAREField = value;
                    this.RaisePropertyChanged("VALOARE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDetails", Namespace="http://schemas.datacontract.org/2004/07/EF2")]
    [System.SerializableAttribute()]
    public partial class OrderDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ORDERIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFClient.ProxyReport.Order OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRODUSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short SERIALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal VALOAREField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ORDERID {
            get {
                return this.ORDERIDField;
            }
            set {
                if ((this.ORDERIDField.Equals(value) != true)) {
                    this.ORDERIDField = value;
                    this.RaisePropertyChanged("ORDERID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFClient.ProxyReport.Order Order {
            get {
                return this.OrderField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderField, value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRODUS {
            get {
                return this.PRODUSField;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUSField, value) != true)) {
                    this.PRODUSField = value;
                    this.RaisePropertyChanged("PRODUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short SERIAL {
            get {
                return this.SERIALField;
            }
            set {
                if ((this.SERIALField.Equals(value) != true)) {
                    this.SERIALField = value;
                    this.RaisePropertyChanged("SERIAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal VALOARE {
            get {
                return this.VALOAREField;
            }
            set {
                if ((this.VALOAREField.Equals(value) != true)) {
                    this.VALOAREField = value;
                    this.RaisePropertyChanged("VALOARE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyReport.IReportService")]
    public interface IReportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetAllCustomers", ReplyAction="http://tempuri.org/IReportService/GetAllCustomersResponse")]
        System.Collections.Generic.List<WCFClient.ProxyReport.Customer> GetAllCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetAllCustomers", ReplyAction="http://tempuri.org/IReportService/GetAllCustomersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WCFClient.ProxyReport.Customer>> GetAllCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetAllOrdersForCustomer", ReplyAction="http://tempuri.org/IReportService/GetAllOrdersForCustomerResponse")]
        System.Collections.Generic.List<WCFClient.ProxyReport.Order> GetAllOrdersForCustomer(short _customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetAllOrdersForCustomer", ReplyAction="http://tempuri.org/IReportService/GetAllOrdersForCustomerResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WCFClient.ProxyReport.Order>> GetAllOrdersForCustomerAsync(short _customerId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportServiceChannel : WCFClient.ProxyReport.IReportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportServiceClient : System.ServiceModel.ClientBase<WCFClient.ProxyReport.IReportService>, WCFClient.ProxyReport.IReportService {
        
        public ReportServiceClient() {
        }
        
        public ReportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<WCFClient.ProxyReport.Customer> GetAllCustomers() {
            return base.Channel.GetAllCustomers();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WCFClient.ProxyReport.Customer>> GetAllCustomersAsync() {
            return base.Channel.GetAllCustomersAsync();
        }
        
        public System.Collections.Generic.List<WCFClient.ProxyReport.Order> GetAllOrdersForCustomer(short _customerId) {
            return base.Channel.GetAllOrdersForCustomer(_customerId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WCFClient.ProxyReport.Order>> GetAllOrdersForCustomerAsync(short _customerId) {
            return base.Channel.GetAllOrdersForCustomerAsync(_customerId);
        }
    }
}
